[package]
name = "osclan-assembler"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = { version = "0.3", features = [ "paw" ] }
anyhow = "1.0.98"
regex = "1.11.1"
enum_stringify = "0.6.3"
